filebeat:
    prospectors:
        -
            paths:
            - "/data/*"
            input_type: log
            fields:
                source: "test_harness"
            fields_under_root: true
output:
    logstash:
        hosts: ["logstash:5000"]
